name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: synapse-490402
  SERVICE_NAME: synapse-service
  REGION: us-central1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Add "id-token" with the intended permissions for Workload Identity Federation
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/35854253693/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: '35854253693-compute@developer.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Submit to Cloud Build
        run: |
          gcloud builds submit --project="${{ env.PROJECT_ID }}" --config cloudbuild.yaml .
